# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Picture.delete_all
Follow.delete_all
Like.delete_all
Comment.delete_all

guest = User.create!({username: "gunther", name: "Gunther", password: 'password', img_url: 'https://res.cloudinary.com/dchen3/image/upload/v1528934443/FullstackPicturesSeedData/gunther_profile.jpg'})
ross = User.create!({username: 'dr_ross', name: "Ross Geller", password: "password1", img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934437/FullstackPicturesSeedData/ross_profile.png"})
rachel = User.create!({username: 'rach', name: "Rachel Green", password: "password1",img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934430/FullstackPicturesSeedData/Rachel_Green_profile.jpg"})
joey = User.create!({username: 'drake_ramoray', name: "Joey Tribbiani", password: "password1", img_url:"https://res.cloudinary.com/dchen3/image/upload/v1528934422/FullstackPicturesSeedData/joey_profile.jpg"})
chandler = User.create!({username: 'bing', name: "Chandler Bing", password: "password1",img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934417/chandle_profile.jpg"})
monica = User.create!({username: 'chef_geller', name: "Monica Geller", password: "password1",img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934412/monica_profile.jpg"})
phoebe = User.create!({username: 'smelly_cat', name: "Phoebe Buffay", password: "password1", img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934401/phoebe_profile.jpg"})
mike = User.create!({username: 'mike', name: 'Mike Hannigan', password: 'password1', img_url: "http://res.cloudinary.com/dchen3/image/upload/c_scale,w_327/v1528994395/FullstackPicturesSeedData/Mike_Hannigan.jpg"})
janice = User.create!({username: 'janice', name: "Janice Hosenstein", password: 'password1', img_url: "http://res.cloudinary.com/dchen3/image/upload/c_scale,w_317/v1528994484/FullstackPicturesSeedData/janice-from-friends-825x580.jpg"})
richard = User.create!({username: 'richard', name: 'Richard Burke', password: 'password1', img_url: 'http://res.cloudinary.com/dchen3/image/upload/c_scale,w_359/v1528998946/FullstackPicturesSeedData/richard_friends.jpg'})
carol = User.create!({username: 'carol', name: 'Carol Willick', password: 'password1', img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528999120/FullstackPicturesSeedData/friends.carol_willick.jpg"})

picture4 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/c_fill,h_500,w_500/v1528934233/armadilloRoss.jpg', user: ross, caption: "Holiday Armadillo!"})
picture10 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934381/picture_10.jpg', user: joey , caption: 'JOEY DOESNT SHARE FOOD'})
picture16 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_501,w_500/v1528934366/picture_16.jpg', user: monica , caption: 'TBT'})
picture19 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934361/picture_19.jpg', user: phoebe, caption: "TRIPLETS"})

picture2 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934244/gunther.jpg', user: guest, caption: "I can dream..."})
picture8 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934351/picture_8.jpg', user: rachel , caption: 'Got a new assistant'})
picture11 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934346/picture_11.jpg', user: joey , caption: 'ITS NOT TRUE'})
picture17 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fill,h_500,w_500/v1528934335/picture_17.jpg', user: monica , caption: 'The routine'})
picture20 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934323/picture_20.jpg', user: phoebe, caption: "smelly cat...smelly cat"})

picture6 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/v1528934310/picture_6.jpg', user: ross, caption: "Vegas"})
picture9 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934305/picture_9.jpg', user: rachel , caption: 'Emma'})
picture15 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934277/picture_15.jpg', user: chandler , caption: 'The best roomie'})
picture1 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/v1528934394/picture1.jpg', user: guest, caption: "Welcome to Central Perk"})
picture21 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934259/picture_21.jpg', user: phoebe , caption: "I GOT MARRIED"})
picture13 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934375/picture_13.jpg', user: chandler , caption: 'best day ever'})
picture3 = Picture.create!({img_url: "https://res.cloudinary.com/dchen3/image/upload/v1528934317/picture_3.jpg", user: guest, caption: "NYC"})
picture18 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934269/picture_18.jpg', user: monica , caption: 'Getting Married!'})
picture14 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934341/picture_14.jpg', user: chandler , caption: 'I married a turkey'})
picture22 = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/v1528910472/dt8rgb3hfsopp4rrfkp0.jpg', user: ross, caption: 'I miss marcel'})
picture7 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934387/picture_7.jpg', user: rachel , caption: 'Me and Ross'})
picture12 = Picture.create!({img_url:'https://res.cloudinary.com/dchen3/image/upload/c_fit,h_500,w_500/v1528934296/picture_12.jpg', user: joey , caption: 'How you doing?'})
picture23 = Picture.create!({img_url: 'https://s33.postimg.cc/q697384a7/Bl8rf_V6_IMAA75_Dp.jpg', user:ross, caption: 'I really though it would pivot'})
picturelast = Picture.create!({img_url: 'https://res.cloudinary.com/dchen3/image/upload/v1528911108/csbcgmbgbnsk6aexuw0i.jpg', user: monica, caption: ':\')'})

follow1 = Follow.create!({user_id: guest.id, followed_id: ross.id})
follow2 = Follow.create!({user_id: guest.id, followed_id: rachel.id})
follow3 = Follow.create!({user_id: guest.id, followed_id: joey.id})
follow4 = Follow.create!({user_id: guest.id, followed_id: chandler.id})
follow5 = Follow.create!({user_id: guest.id, followed_id: monica.id})
follow6 = Follow.create!({user_id: guest.id, followed_id: phoebe.id})
follow7 = Follow.create!({user_id: ross.id, followed_id: guest.id})
follow8 = Follow.create!({user_id: ross.id, followed_id: rachel.id})
follow9 = Follow.create!({user_id: ross.id, followed_id: joey.id})
follow10 = Follow.create!({user_id: ross.id, followed_id: chandler.id})
follow11 = Follow.create!({user_id: ross.id, followed_id: monica.id})
follow12 = Follow.create!({user_id: ross.id, followed_id: phoebe.id})
follow13 = Follow.create!({user_id: rachel.id, followed_id: ross.id})
follow14 = Follow.create!({user_id: rachel.id, followed_id: guest.id})
follow15 = Follow.create!({user_id: rachel.id, followed_id: joey.id})
follow16 = Follow.create!({user_id: rachel.id, followed_id: chandler.id})
follow17 = Follow.create!({user_id: rachel.id, followed_id: monica.id})
follow18 = Follow.create!({user_id: rachel.id, followed_id: phoebe.id})
follow19 = Follow.create!({user_id: joey.id, followed_id: ross.id})
follow20 = Follow.create!({user_id: joey.id, followed_id: rachel.id})
follow22 = Follow.create!({user_id: joey.id, followed_id: chandler.id})
follow23 = Follow.create!({user_id: joey.id, followed_id: monica.id})
follow24 = Follow.create!({user_id: joey.id, followed_id: phoebe.id})
follow25 = Follow.create!({user_id: chandler.id, followed_id: ross.id})
follow26 = Follow.create!({user_id: chandler.id, followed_id: rachel.id})
follow27 = Follow.create!({user_id: chandler.id, followed_id: joey.id})
follow29 = Follow.create!({user_id: chandler.id, followed_id: monica.id})
follow30 = Follow.create!({user_id: chandler.id, followed_id: phoebe.id})
follow31 = Follow.create!({user_id: monica.id, followed_id: ross.id})
follow32 = Follow.create!({user_id: monica.id, followed_id: rachel.id})
follow33 = Follow.create!({user_id: monica.id, followed_id: joey.id})
follow34 = Follow.create!({user_id: monica.id, followed_id: chandler.id})
follow35 = Follow.create!({user_id: monica.id, followed_id: phoebe.id})
follow36 = Follow.create!({user_id: phoebe.id, followed_id: ross.id})
follow37 = Follow.create!({user_id: phoebe.id, followed_id: rachel.id})
follow38 = Follow.create!({user_id: phoebe.id, followed_id: joey.id})
follow39 = Follow.create!({user_id: phoebe.id, followed_id: monica.id})
follow40 = Follow.create!({user_id: phoebe.id, followed_id: chandler.id})
follow41 = Follow.create!({user_id: phoebe.id, followed_id: guest.id})
follow42 = Follow.create!({user_id: guest.id, followed_id: mike.id})
follow43 = Follow.create!({user_id: guest.id, followed_id: janice.id})
follow44 = Follow.create!({user_id: guest.id, followed_id: richard.id})
follow45 = Follow.create!({user_id: guest.id, followed_id: carol.id})

likes = Like.create!({user_id: ross.id, picture_id: picturelast.id})
likes2 = Like.create!({user_id: rachel.id, picture_id: picturelast.id})
likes3 = Like.create!({user_id: chandler.id, picture_id: picturelast.id})
likes4 = Like.create!({user_id: joey.id, picture_id: picturelast.id})
likes5 = Like.create!({user_id: phoebe.id, picture_id: picturelast.id})
likes6 = Like.create!({user_id: mike.id, picture_id: picturelast.id})
likes7 = Like.create!({user_id: richard.id, picture_id: picturelast.id})
comment1 = Comment.create!({user_id: phoebe.id, picture_id: picturelast.id, body: "There's us!"})

likes8 = Like.create!({user_id: carol.id, picture_id: picture23.id})
likes9 = Like.create!({user_id: rachel.id, picture_id: picture23.id})
likes11 = Like.create!({user_id: joey.id, picture_id: picture23.id})
likes12 = Like.create!({user_id: phoebe.id, picture_id: picture23.id})
likes13 = Like.create!({user_id: mike.id, picture_id: picture23.id})
likes14 = Like.create!({user_id: richard.id, picture_id: picture23.id})
comment2 = Comment.create!({user_id: rachel.id, picture_id: picture23.id, body: "Ross...you really should have paid for shipping."})
comment3 = Comment.create!({user_id: chandler.id, picture_id: picture23.id, body: "SHUT UP!"})


likes15 = Like.create!({user_id: chandler.id, picture_id: picture12.id})
likes16 = Like.create!({user_id: rachel.id, picture_id: picture12.id})
likes17 = Like.create!({user_id: joey.id, picture_id: picture12.id})
likes18 = Like.create!({user_id: phoebe.id, picture_id: picture12.id})
likes19 = Like.create!({user_id: ross.id, picture_id: picture12.id})
comment4 = Comment.create!({user_id: guest.id, picture_id: picture12.id, body: "I love this show!"})
comment5 = Comment.create!({user_id: rachel.id, picture_id: picture12.id, body: "Me TOO!"})

likes20 = Like.create!({user_id: chandler.id, picture_id: picture22.id})
likes21 = Like.create!({user_id: rachel.id, picture_id: picture22.id})
likes22 = Like.create!({user_id: joey.id, picture_id: picture22.id})
likes23 = Like.create!({user_id: phoebe.id, picture_id: picture22.id})
likes24 = Like.create!({user_id: mike.id, picture_id: picture22.id})
comment6 = Comment.create!({user_id: chandler.id, picture_id: picture22.id, body: "Hey, that monkey's got a Ross on its butt!"})

likes25 = Like.create!({user_id: monica.id, picture_id: picture14.id})
likes26 = Like.create!({user_id: rachel.id, picture_id: picture14.id})
likes27 = Like.create!({user_id: joey.id, picture_id: picture14.id})
likes28 = Like.create!({user_id: phoebe.id, picture_id: picture14.id})
likes29 = Like.create!({user_id: mike.id, picture_id: picture14.id})
comment7 = Comment.create!({user_id: ross.id, picture_id: picture14.id, body: "Im not even going to ask"})
comment8 = Comment.create!({user_id: joey.id, picture_id: picture14.id, body: "AHHH"})
comment9 = Comment.create!({user_id: janice.id, picture_id: picture14.id, body: "HIIIIII Chandler Bing!!!"})

likes30 = Like.create!({user_id: chandler.id, picture_id: picture18.id})
likes31 = Like.create!({user_id: rachel.id, picture_id: picture18.id})
likes32 = Like.create!({user_id: joey.id, picture_id: picture18.id})
likes33 = Like.create!({user_id: phoebe.id, picture_id: picture18.id})
likes34 = Like.create!({user_id: ross.id, picture_id: picture18.id})
likes35 = Like.create!({user_id: richard.id, picture_id: picture18.id})
comment10 = Comment.create!({user_id: chandler.id, picture_id: picture18.id, body: "Hi honey"})
comment11 = Comment.create!({user_id: richard.id, picture_id: picture18.id, body: "congrats Monica"})

likes36 = Like.create!({user_id: monica.id, picture_id: picture13.id})
likes37 = Like.create!({user_id: rachel.id, picture_id: picture13.id})
likes38 = Like.create!({user_id: joey.id, picture_id: picture13.id})
likes39 = Like.create!({user_id: phoebe.id, picture_id: picture13.id})
likes40 = Like.create!({user_id: ross.id, picture_id: picture13.id})
comment12 = Comment.create!({user_id: janice.id, picture_id: picture13.id, body: "OH MY GOD!"})

likes41 = Like.create!({user_id: monica.id, picture_id: picture21.id})
likes42 = Like.create!({user_id: rachel.id, picture_id: picture21.id})
likes43 = Like.create!({user_id: joey.id, picture_id: picture21.id})
likes44 = Like.create!({user_id: chandler.id, picture_id: picture21.id})
likes45 = Like.create!({user_id: ross.id, picture_id: picture21.id})
likes46 = Like.create!({user_id: mike.id, picture_id: picture21.id})
comment13 = Comment.create!({user_id: mike.id, picture_id: picture21.id, body: "Whooo!"})

likes47 = Like.create!({user_id: monica.id, picture_id: picture15.id})
likes48 = Like.create!({user_id: rachel.id, picture_id: picture15.id})
likes49 = Like.create!({user_id: joey.id, picture_id: picture15.id})
likes50 = Like.create!({user_id: ross.id, picture_id: picture15.id})
comment14 = Comment.create!({user_id: ross.id, picture_id: picture15.id, body: "Where am I?"})
comment15 = Comment.create!({user_id: joey.id, picture_id: picture15.id, body: "There's me!"})

likes51 = Like.create!({user_id: monica.id, picture_id: picture9.id})
likes52 = Like.create!({user_id: phoebe.id, picture_id: picture9.id})
likes53 = Like.create!({user_id: joey.id, picture_id: picture9.id})
likes54 = Like.create!({user_id: ross.id, picture_id: picture9.id})

likes51 = Like.create!({user_id: monica.id, picture_id: picture6.id})
likes52 = Like.create!({user_id: phoebe.id, picture_id: picture6.id})
likes53 = Like.create!({user_id: joey.id, picture_id: picture6.id})
likes54 = Like.create!({user_id: chandler.id, picture_id: picture6.id})
comment16 = Comment.create!({user_id: guest.id, picture_id: picture6.id, body: "You are so lucky..."})
comment17 = Comment.create!({user_id: rachel.id, picture_id: picture6.id, body: "...."})
comment18 = Comment.create!({user_id: chandler.id, picture_id: picture6.id, body: "And I thought my Vegas trip was bad."})

likes55 = Like.create!({user_id: monica.id, picture_id: picture20.id})
likes56 = Like.create!({user_id: rachel.id, picture_id: picture20.id})
likes57 = Like.create!({user_id: joey.id, picture_id: picture20.id})
likes58 = Like.create!({user_id: chandler.id, picture_id: picture20.id})
likes59 = Like.create!({user_id: ross.id, picture_id: picture20.id})
likes60 = Like.create!({user_id: mike.id, picture_id: picture20.id})
comment19 = Comment.create!({user_id: mike.id, picture_id: picture20.id, body: "!!!"})

likes61 = Like.create!({user_id: ross.id, picture_id: picture17.id})
likes62 = Like.create!({user_id: phoebe.id, picture_id: picture17.id})
likes63 = Like.create!({user_id: chandler.id, picture_id: picture17.id})

likes64 = Like.create!({user_id: monica.id, picture_id: picture8.id})
likes65 = Like.create!({user_id: phoebe.id, picture_id: picture8.id})
likes66 = Like.create!({user_id: chandler.id, picture_id: picture8.id})

likes67 = Like.create!({user_id: ross.id, picture_id: picture11.id})
likes68 = Like.create!({user_id: mike.id, picture_id: picture11.id})
likes69 = Like.create!({user_id: chandler.id, picture_id: picture11.id})

likes70 = Like.create!({user_id: rachel.id, picture_id: picture19.id})
likes71 = Like.create!({user_id: monica.id, picture_id: picture19.id})
likes72 = Like.create!({user_id: joey.id, picture_id: picture19.id})

likes73 = Like.create!({user_id: rachel.id, picture_id: picture16.id})
likes74 = Like.create!({user_id: ross.id, picture_id: picture16.id})
likes75 = Like.create!({user_id: joey.id, picture_id: picture16.id})
likes76 = Like.create!({user_id: chandler.id, picture_id: picture16.id})
comment20 = Comment.create!({user_id: joey.id, picture_id: picture16.id, body: "Someone ate MONICA!"})

likes77 = Like.create!({user_id: monica.id, picture_id: picture7.id})
likes78 = Like.create!({user_id: ross.id, picture_id: picture7.id})
likes79 = Like.create!({user_id: joey.id, picture_id: picture7.id})
likes80 = Like.create!({user_id: chandler.id, picture_id: picture7.id})

comment21 = Comment.create!({user_id: ross.id, picture_id: picture2.id, body: "..."})
comment22 = Comment.create!({user_id: rachel.id, picture_id: picture2.id, body: "???"})

likes81 = Like.create!({user_id: monica.id, picture_id: picture1.id})
likes82 = Like.create!({user_id: rachel.id, picture_id: picture1.id})
likes83 = Like.create!({user_id: joey.id, picture_id: picture1.id})
likes84 = Like.create!({user_id: chandler.id, picture_id: picture1.id})
likes85 = Like.create!({user_id: ross.id, picture_id: picture1.id})
likes86 = Like.create!({user_id: mike.id, picture_id: picture1.id})

likes87 = Like.create!({user_id: monica.id, picture_id: picture3.id})
likes88 = Like.create!({user_id: rachel.id, picture_id: picture3.id})
likes89 = Like.create!({user_id: joey.id, picture_id: picture3.id})
likes90 = Like.create!({user_id: chandler.id, picture_id: picture3.id})
likes91 = Like.create!({user_id: ross.id, picture_id: picture3.id})
